// Code generated by aliaser. DO NOT EDIT.

package gin

import "github.com/gin-gonic/gin"

const (
	AuthUserKey             = gin.AuthUserKey
	BindKey                 = gin.BindKey
	BodyBytesKey            = gin.BodyBytesKey
	ContextKey              = gin.ContextKey
	DebugMode               = gin.DebugMode
	EnvGinMode              = gin.EnvGinMode
	ErrorTypeAny            = gin.ErrorTypeAny
	ErrorTypeBind           = gin.ErrorTypeBind
	ErrorTypeNu             = gin.ErrorTypeNu
	ErrorTypePrivate        = gin.ErrorTypePrivate
	ErrorTypePublic         = gin.ErrorTypePublic
	ErrorTypeRender         = gin.ErrorTypeRender
	MIMEHTML                = gin.MIMEHTML
	MIMEJSON                = gin.MIMEJSON
	MIMEMultipartPOSTForm   = gin.MIMEMultipartPOSTForm
	MIMEPOSTForm            = gin.MIMEPOSTForm
	MIMEPlain               = gin.MIMEPlain
	MIMETOML                = gin.MIMETOML
	MIMEXML                 = gin.MIMEXML
	MIMEXML2                = gin.MIMEXML2
	MIMEYAML                = gin.MIMEYAML
	PlatformCloudflare      = gin.PlatformCloudflare
	PlatformGoogleAppEngine = gin.PlatformGoogleAppEngine
	ReleaseMode             = gin.ReleaseMode
	TestMode                = gin.TestMode
	Version                 = gin.Version
)

var (
	DebugPrintRouteFunc = gin.DebugPrintRouteFunc
	DefaultErrorWriter  = gin.DefaultErrorWriter
	DefaultWriter       = gin.DefaultWriter
)

// Functions
var (
	BasicAuth                              = gin.BasicAuth
	BasicAuthForRealm                      = gin.BasicAuthForRealm
	Bind                                   = gin.Bind
	CreateTestContext                      = gin.CreateTestContext
	CreateTestContextOnly                  = gin.CreateTestContextOnly
	CustomRecovery                         = gin.CustomRecovery
	CustomRecoveryWithWriter               = gin.CustomRecoveryWithWriter
	Default                                = gin.Default
	Dir                                    = gin.Dir
	DisableBindValidation                  = gin.DisableBindValidation
	DisableConsoleColor                    = gin.DisableConsoleColor
	EnableJsonDecoderDisallowUnknownFields = gin.EnableJsonDecoderDisallowUnknownFields
	EnableJsonDecoderUseNumber             = gin.EnableJsonDecoderUseNumber
	ErrorLogger                            = gin.ErrorLogger
	ErrorLoggerT                           = gin.ErrorLoggerT
	ForceConsoleColor                      = gin.ForceConsoleColor
	IsDebugging                            = gin.IsDebugging
	Logger                                 = gin.Logger
	LoggerWithConfig                       = gin.LoggerWithConfig
	LoggerWithFormatter                    = gin.LoggerWithFormatter
	LoggerWithWriter                       = gin.LoggerWithWriter
	Mode                                   = gin.Mode
	New                                    = gin.New
	Recovery                               = gin.Recovery
	RecoveryWithWriter                     = gin.RecoveryWithWriter
	SetMode                                = gin.SetMode
	WrapF                                  = gin.WrapF
	WrapH                                  = gin.WrapH
)

type (
	Accounts           = gin.Accounts
	Context            = gin.Context
	Engine             = gin.Engine
	Error              = gin.Error
	ErrorType          = gin.ErrorType
	H                  = gin.H
	HandlerFunc        = gin.HandlerFunc
	HandlersChain      = gin.HandlersChain
	IRouter            = gin.IRouter
	IRoutes            = gin.IRoutes
	LogFormatter       = gin.LogFormatter
	LogFormatterParams = gin.LogFormatterParams
	LoggerConfig       = gin.LoggerConfig
	Negotiate          = gin.Negotiate
	Param              = gin.Param
	Params             = gin.Params
	RecoveryFunc       = gin.RecoveryFunc
	ResponseWriter     = gin.ResponseWriter
	RouteInfo          = gin.RouteInfo
	RouterGroup        = gin.RouterGroup
	RoutesInfo         = gin.RoutesInfo
)
