#!/bin/sh

set -e

# Generate aliases for uuid package from github.com/google/uuid and write to
# uuid/alias.go file. It also runs go mod tidy to remove unused dependencies.
go run -mod=mod github.com/marcozac/go-aliaser/cmd/aliaser generate \
	--from="github.com/google/uuid" \
	--file="uuid/alias.go" \
	--package="uuid" \
	--header="// Code generated by go-aliaser. DO NOT EDIT." \
	&& go mod tidy
