package main

import (
	"log"

	"github.com/marcozac/go-aliaser"
)

// main generates the aliases for the gin package and writes them to gin/alias.go.
func main() {
	src, err := aliaser.Load("github.com/gin-gonic/gin")
	if err != nil {
		log.Fatal(err)
	}
	err = aliaser.Generate(&aliaser.Alias{
		PkgName: "gin",
		Out:     "gin/alias.go",
		Src:     src,
		Header:  "// Code generated by go-aliaser. DO NOT EDIT.",
	})
	if err != nil {
		log.Fatal(err)
	}
}
