// Code generated by aliaser. DO NOT EDIT.

package uuid

import "github.com/google/uuid"

const (
	Future    = uuid.Future
	Group     = uuid.Group
	Invalid   = uuid.Invalid
	Microsoft = uuid.Microsoft
	Org       = uuid.Org
	Person    = uuid.Person
	RFC4122   = uuid.RFC4122
	Reserved  = uuid.Reserved
)

var (
	Max           = uuid.Max
	NameSpaceDNS  = uuid.NameSpaceDNS
	NameSpaceOID  = uuid.NameSpaceOID
	NameSpaceURL  = uuid.NameSpaceURL
	NameSpaceX500 = uuid.NameSpaceX500
	Nil           = uuid.Nil
)

// Functions
var (
	ClockSequence        = uuid.ClockSequence
	DisableRandPool      = uuid.DisableRandPool
	EnableRandPool       = uuid.EnableRandPool
	FromBytes            = uuid.FromBytes
	GetTime              = uuid.GetTime
	IsInvalidLengthError = uuid.IsInvalidLengthError
	Must                 = uuid.Must
	MustParse            = uuid.MustParse
	New                  = uuid.New
	NewDCEGroup          = uuid.NewDCEGroup
	NewDCEPerson         = uuid.NewDCEPerson
	NewDCESecurity       = uuid.NewDCESecurity
	NewHash              = uuid.NewHash
	NewMD5               = uuid.NewMD5
	NewRandom            = uuid.NewRandom
	NewRandomFromReader  = uuid.NewRandomFromReader
	NewSHA1              = uuid.NewSHA1
	NewString            = uuid.NewString
	NewUUID              = uuid.NewUUID
	NewV6                = uuid.NewV6
	NewV7                = uuid.NewV7
	NewV7FromReader      = uuid.NewV7FromReader
	NodeID               = uuid.NodeID
	NodeInterface        = uuid.NodeInterface
	Parse                = uuid.Parse
	ParseBytes           = uuid.ParseBytes
	SetClockSequence     = uuid.SetClockSequence
	SetNodeID            = uuid.SetNodeID
	SetNodeInterface     = uuid.SetNodeInterface
	SetRand              = uuid.SetRand
	Validate             = uuid.Validate
)

type (
	Domain   = uuid.Domain
	NullUUID = uuid.NullUUID
	Time     = uuid.Time
	UUID     = uuid.UUID
	UUIDs    = uuid.UUIDs
	Variant  = uuid.Variant
	Version  = uuid.Version
)
